export const ARABIC_MAPPING: Record<string, string> = {
  // Countries
  "Algeria": "الجزائر",
  "Bahrain": "البحرين",
  "Comoros": "جزر القمر",
  "Djibouti": "جيبوتي",
  "Egypt": "مصر",
  "Iraq": "العراق",
  "Jordan": "الأردن",
  "Kuwait": "الكويت",
  "Lebanon": "لبنان",
  "Libya": "ليبيا",
  "Mauritania": "موريتانيا",
  "Morocco": "المغرب",
  "Oman": "عمان",
  "Palestine": "فلسطين",
  "Qatar": "قطر",
  "Saudi Arabia": "المملكة العربية السعودية",
  "Somalia": "الصومال",
  "Sudan": "السودان",
  "Syria": "سوريا",
  "Tunisia": "تونس",
  "United Arab Emirates": "الإمارات العربية المتحدة",
  "Yemen": "اليمن",

  // Egypt (Standard and Library variations)
  "Al Iskandariyah": "الإسكندرية",
  "Alexandria": "الإسكندرية",
  "Al Isma'iliyah": "الإسماعيلية",
  "Ismailia": "الإسماعيلية",
  "Al Jizah": "الجيزة",
  "Giza": "الجيزة",
  "Al Minufiyah": "المنوفية",
  "Monufia": "المنوفية",
  "Al Minya": "المنيا",
  "Minya": "المنيا",
  "Al Qahirah": "القاهرة",
  "Cairo": "القاهرة",
  "Al Qalyubiyah": "القليوبية",
  "Qalyubia": "القليوبية",
  "Al Wadi al Jadid": "الوادي الجديد",
  "New Valley": "الوادي الجديد",
  "Ash Sharqiyah": "الشرقية",
  "Sharkia": "الشرقية",
  "Aswan": "أسوان",
  "Asyut": "أسيوط",
  "Bani Suwayf": "بني سويف",
  "Beni Suef": "بني سويف",
  "Bur Sa'id": "بورسعيد",
  "Port Said": "بورسعيد",
  "Dumyat": "دمياط",
  "Damietta": "دمياط",
  "Janub Sina'": "جنوب سيناء",
  "South Sinai": "جنوب سيناء",
  "Kafr ash Shaykh": "كفر الشيخ",
  "Kafr el-Sheikh": "كفر الشيخ",
  "Matruh": "مطروح",
  "Matrouh": "مطروح",
  "Qina": "قنا",
  "Qena": "قنا",
  "Shimal Sina'": "شمال سيناء",
  "North Sinai": "شمال سيناء",
  "Suhaj": "سوهاج",
  "Sohag": "سوهاج",
  "Luxor": "الأقصر",
  "Al Uqsur": "الأقصر",
  "Dakahlia": "الدقهلية",
  "Al Daqahliyah": "الدقهلية",
  "Red Sea": "البحر الأحمر",
  "Al Bahr al Ahmar": "البحر الأحمر",
  "Beheira": "البحيرة",
  "Al Buhayrah": "البحيرة",
  "Faiyum": "الفيوم",
  "Al Fayyum": "الفيوم",
  "Gharbia": "الغربية",
  "Al Gharbiyah": "الغربية",
  "Suez": "السويس",
  "As Suways": "السويس",

  // Saudi Arabia
  "Ar Riyad": "الرياض",
  "Riyadh": "الرياض",
  "Makkah al Mukarramah": "مكة المكرمة",
  "Makkah": "مكة المكرمة",
  "Al Madinah al Munawwarah": "المدينة المنورة",
  "Madinah": "المدينة المنورة",
  "Eastern Province": "المنطقة الشرقية",
  "Al Qassim": "القصيم",
  "Asir": "عسير",
  "Tabuk": "تبوك",
  "Ha'il": "حائل",
  "Al Hudud ash Shamaliyah": "الحدود الشمالية",
  "Jazan": "جازان",
  "Najran": "نجران",
  "Al Bahah": "الباحة",
  "Al Jawf": "الجوف",

  // UAE
  "Abu Dhabi": "أبو ظبي",
  "Dubai": "دبي",
  "Sharjah": "الشارقة",
  "Ajman": "عجمان",
  "Fujairah": "الفجيرة",
  "Ras al-Khaimah": "رأس الخيمة",
  "Umm al-Quwain": "أم القيوين",

  // Kuwait
  "Al Asimah": "العاصمة",
  "Hawalli": "حولي",
  "Al Farwaniyah": "الفروانية",
  "Mubarak al-Kabeer": "مبارك الكبير",
  "Al Ahmadi": "الأحمدي",
  "Al Jahra": "الجهراء",

  // Qatar
  "Ad Dawhah": "الدوحة",
  "Doha": "الدوحة",
  "Al Khawr wa adh Dhakhirah": "الخور والذخيرة",
  "Al Wakrah": "الوكرة",
  "Ar Rayyan": "الريان",
  "Ash Shamal": "الشمال",
  "Az Za'ayin": "الظعاين",
  "Umm Salal": "أم صلال",
  "Al-Shahaniya": "الشيحانية",

  // Jordan
  "Amman": "عمان",
  "Irbid": "إربد",
  "Zarqa": "الزرقاء",
  "Mafraq": "المفرق",
  "Ajloun": "عجلون",
  "Jarash": "جرش",
  "Madaba": "مأدبا",
  "Balqa": "البلقاء",
  "Karak": "الكرك",
  "Tafilah": "الطفيلة",
  "Ma'an": "معان",
  "Aqaba": "العقبة",

  // Palestine
  "Jerusalem": "القدس",
  "Gaza": "غزة",
  "Hebron": "الخليل",
  "Nablus": "نابلس",
  "Ramallah and Al-Bireh": "رام الله والبيرة",
  "Jenin": "جنين",
  "Tulkarm": "طولكرم",
  "Qalqilya": "قلقيلية",
  "Bethlehem": "بيت لحم",
  "Salfit": "سلفيت",
  "Tubas": "طوباس",
  "Jericho": "أريحا",
  "Khan Yunis": "خان يونس",
  "Rafah": "رفح",

  // Iraq
  "Baghdad": "بغداد",
  "Basra": "البصرة",
  "Nineveh": "نينوى",
  "Erbil": "أربيل",
  "Sulaymaniyah": "السليمانية",
  "Kirkuk": "كركوك",
  "Najaf": "النجف",
  "Karbala": "كربلاء",
  "Anbar": "الأنبار",

  // ... and others
};

export const getLocalizedName = (name: string, lang: string) => {
  if (lang !== "ar") return name;
  
  // 1. Try exact match
  if (ARABIC_MAPPING[name]) return ARABIC_MAPPING[name];
  
  // 2. Try without common suffixes (Governorate, Emirate, Province, etc.)
  const cleaned = name.replace(/\s+(Governorate|Emirate|Province|District|State|Region)$/i, "").trim();
  if (ARABIC_MAPPING[cleaned]) return ARABIC_MAPPING[cleaned];
  
  // 3. Fallback to original name
  return name;
};
